### PR TITLE
Fix #702 - geom_density2d: Internal error with None values in data

### LINKED ISSUE #702: geom_density2d: Internal error with None values in data
Example:

```python
data = {
    'x': [0, 1, None],
    'y': [0, 1, None],
}
ggplot(data, aes('x', 'y')) + geom_density2d()
```

Output:

> Internal error: NullPointerException : \<no message\>

### PR DESCRIPTION
**Pull request by ASmirnov-HORIS**

### CODE REVIEW

File: plot-base-portable/src/commonMain/kotlin/jetbrains/datalore/plot/base/stat/Density2dStat.kt [hunk 1]
```diff
@@ -42,8 +42,11 @@ class Density2dStat constructor(
             return withEmptyStatValues()
         }
 
-        val xVector = data.getNumeric(TransformVar.X)
-        val yVector = data.getNumeric(TransformVar.Y)
+        val xs = data.getNumeric(TransformVar.X)
+        val ys = data.getNumeric(TransformVar.Y)
+        val (xVector, yVector) = (xs zip ys)
+            .filter { it.first?.isFinite() == true && it.second?.isFinite() == true }
```
Comment (alshan) [inline plot-base-portable/src/commonMain/kotlin/jetbrains/datalore/plot/base/stat/Density2dStat.kt:48]: Try to use SeriesUtil.allFinite()

**Review by alshan — CHANGES_REQUESTED** [review]
